sonar.projectKey=20umutcan_TicketSystem
sonar.organization=20umutcan-github   
sonar.host.url=https://sonarcloud.io

# C# projeleri için
sonar.language=cs
sonar.sourceEncoding=UTF-8
sonar.sources=TicketAPI,TicketMVC
sonar.tests=TicketAPI.Tests,TicketMVC.Tests   
