// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketAPI.Models;

#nullable disable

namespace TicketAPI.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20260306150708_V2_RedesignWithSeed")]
    partial class V2_RedesignWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TicketAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Taşınabilir notebook ve laptop modelleri",
                            Name = "Dizüstü Bilgisayar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kasa ve all-in-one masaüstü sistemler",
                            Name = "Masaüstü Bilgisayar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lazer, inkjet yazıcılar ve tarayıcı cihazlar",
                            Name = "Yazıcı & Tarayıcı"
                        },
                        new
                        {
                            Id = 4,
                            Description = "LCD, LED ve OLED ekranlar",
                            Name = "Monitör"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Router, switch, access point ve modem",
                            Name = "Ağ Cihazları"
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Intel Core i5-1235U, 8GB DDR4, 512GB SSD, 15.6\" FHD IPS, Windows 11",
                            Name = "Asus VivoBook 15 X1502"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Intel Core i7-1165G7, 16GB DDR4, 512GB SSD, 15.6\" FHD, Windows 11 Home",
                            Name = "Lenovo IdeaPad 3 15ITL6"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Intel Core i5-1235U, 8GB DDR4, 256GB SSD+1TB HDD, 15.6\" FHD, Windows 11",
                            Name = "HP Pavilion 15-eg2049nt"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Intel Core i5-1235U, 8GB DDR4, 512GB SSD, NVIDIA MX550, 15.6\" FHD",
                            Name = "Acer Aspire 5 A515-57G"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Intel Core i5-12500, 8GB DDR4, 256GB SSD, Windows 11 Pro, kurumsal kullanım",
                            Name = "Dell OptiPlex 3000 MT"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Intel Core i7-12700, 16GB DDR5, 512GB SSD NVMe, Windows 11 Pro",
                            Name = "HP EliteDesk 800 G9 SFF"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Intel Core i5-10400, 8GB DDR4, 256GB SSD, DVD-RW, Windows 10 Pro",
                            Name = "Lenovo ThinkCentre M70s"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Çok Fonksiyonlu Lazer Yazıcı, Dubleks, Wi-Fi, Tarayıcı",
                            Name = "Brother DCP-L2540DW"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Lazer, Faks, Tarayıcı, Fotokopi, Çift Taraflı Baskı, Ethernet/Wi-Fi",
                            Name = "HP LaserJet Pro MFP M428fdw"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Renkli mürekkep tanklı yazıcı, Wi-Fi, tarayıcı, düşük maliyet",
                            Name = "Epson EcoTank ET-2800"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "27\" VA, 1080p, 165Hz, 1ms, FreeSync Premium, oyun monitörü",
                            Name = "Samsung 27\" Odyssey G3 S27AG320"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "24\" IPS, 1080p, 75Hz, AMD FreeSync, ince çerçeve, ofis kullanımı",
                            Name = "LG 24MK430H-B"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Wi-Fi 6, AX3000, 4 anten, Gigabit, beamforming, EasyMesh destekli",
                            Name = "TP-Link Archer AX55"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "10-Port Yönetilebilir PoE Gigabit Switch, Layer 3, VLAN, QoS",
                            Name = "Cisco SG300-10PP 10-Port"
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketAPI.Models.WarrantyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WarrantyParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PartName = "Anakart",
                            ProductId = 1,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 2,
                            PartName = "RAM",
                            ProductId = 1,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 3,
                            PartName = "SSD",
                            ProductId = 1,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 4,
                            PartName = "Ekran Paneli",
                            ProductId = 1,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 5,
                            PartName = "Batarya",
                            ProductId = 1,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 6,
                            PartName = "Klavye",
                            ProductId = 1,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 7,
                            PartName = "Anakart",
                            ProductId = 2,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 8,
                            PartName = "RAM",
                            ProductId = 2,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 9,
                            PartName = "SSD",
                            ProductId = 2,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 10,
                            PartName = "Ekran Paneli",
                            ProductId = 2,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 11,
                            PartName = "Batarya",
                            ProductId = 2,
                            WarrantyMonths = 6
                        },
                        new
                        {
                            Id = 12,
                            PartName = "Şarj Adaptörü",
                            ProductId = 2,
                            WarrantyMonths = 6
                        },
                        new
                        {
                            Id = 13,
                            PartName = "Anakart",
                            ProductId = 3,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 14,
                            PartName = "RAM",
                            ProductId = 3,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 15,
                            PartName = "SSD",
                            ProductId = 3,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 16,
                            PartName = "HDD",
                            ProductId = 3,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 17,
                            PartName = "Batarya",
                            ProductId = 3,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 18,
                            PartName = "Klavye",
                            ProductId = 3,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 19,
                            PartName = "Ekran Menteşe",
                            ProductId = 3,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 20,
                            PartName = "Anakart",
                            ProductId = 4,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 21,
                            PartName = "Ekran Kartı (NVIDIA MX550)",
                            ProductId = 4,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 22,
                            PartName = "RAM",
                            ProductId = 4,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 23,
                            PartName = "SSD",
                            ProductId = 4,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 24,
                            PartName = "Batarya",
                            ProductId = 4,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 25,
                            PartName = "Fan / Soğutma",
                            ProductId = 4,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 26,
                            PartName = "Anakart",
                            ProductId = 5,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 27,
                            PartName = "İşlemci",
                            ProductId = 5,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 28,
                            PartName = "RAM",
                            ProductId = 5,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 29,
                            PartName = "SSD",
                            ProductId = 5,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 30,
                            PartName = "Güç Kaynağı",
                            ProductId = 5,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 31,
                            PartName = "Anakart",
                            ProductId = 6,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 32,
                            PartName = "İşlemci",
                            ProductId = 6,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 33,
                            PartName = "RAM DDR5",
                            ProductId = 6,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 34,
                            PartName = "SSD NVMe",
                            ProductId = 6,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 35,
                            PartName = "Güç Kaynağı",
                            ProductId = 6,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 36,
                            PartName = "Anakart",
                            ProductId = 7,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 37,
                            PartName = "İşlemci",
                            ProductId = 7,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 38,
                            PartName = "RAM",
                            ProductId = 7,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 39,
                            PartName = "SSD",
                            ProductId = 7,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 40,
                            PartName = "DVD-RW Sürücü",
                            ProductId = 7,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 41,
                            PartName = "Ana Kart",
                            ProductId = 8,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 42,
                            PartName = "Lazer Drum Ünitesi",
                            ProductId = 8,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 43,
                            PartName = "Fuser (Isıtma) Ünitesi",
                            ProductId = 8,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 44,
                            PartName = "Kağıt Besleme Mekanizması",
                            ProductId = 8,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 45,
                            PartName = "Ana Kart",
                            ProductId = 9,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 46,
                            PartName = "Fuser Ünitesi",
                            ProductId = 9,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 47,
                            PartName = "Drum Ünitesi",
                            ProductId = 9,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 48,
                            PartName = "ADF (Otomatik Belge Besleyici)",
                            ProductId = 9,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 49,
                            PartName = "Faks Modülü",
                            ProductId = 9,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 50,
                            PartName = "Ana Kart",
                            ProductId = 10,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 51,
                            PartName = "Mürekkep Pompa Sistemi",
                            ProductId = 10,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 52,
                            PartName = "Baskı Kafası",
                            ProductId = 10,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 53,
                            PartName = "VA Panel",
                            ProductId = 11,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 54,
                            PartName = "Güç Kaynağı Kartı",
                            ProductId = 11,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 55,
                            PartName = "Ana Kart",
                            ProductId = 11,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 56,
                            PartName = "IPS Panel",
                            ProductId = 12,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 57,
                            PartName = "Güç Kaynağı",
                            ProductId = 12,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 58,
                            PartName = "Ana Kart",
                            ProductId = 12,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 59,
                            PartName = "Ana Kart / CPU",
                            ProductId = 13,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 60,
                            PartName = "Wi-Fi 6 Modülü",
                            ProductId = 13,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 61,
                            PartName = "Güç Adaptörü",
                            ProductId = 13,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 62,
                            PartName = "Switching Fabric",
                            ProductId = 14,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 63,
                            PartName = "PoE Güç Modülü",
                            ProductId = 14,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 64,
                            PartName = "Fan",
                            ProductId = 14,
                            WarrantyMonths = 12
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.Product", b =>
                {
                    b.HasOne("TicketAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.HasOne("TicketAPI.Models.Product", "Product")
                        .WithMany("Tickets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TicketAPI.Models.WarrantyPart", b =>
                {
                    b.HasOne("TicketAPI.Models.Product", "Product")
                        .WithMany("WarrantyParts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TicketAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TicketAPI.Models.Product", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("WarrantyParts");
                });
#pragma warning restore 612, 618
        }
    }
}
